name: publish

on:
  release:
    types: [published]
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_PATH: Vestfold.Extensions.Authentication/Vestfold.Extensions.Authentication.csproj
  PROJECT_RELEASE_PATH: Vestfold.Extensions.Authentication/bin/Release
  NUGET_SOURCE: https://api.nuget.org/v3/index.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #Build/pack the project
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and pack project # <GeneratePackageOnBuild>true</GeneratePackageOnBuild> must be added to .csproj
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release

    - name: Publish NuGet package to NuGet.org
      run: dotnet nuget push ${{ env.PROJECT_RELEASE_PATH }}/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ env.NUGET_SOURCE }}
